version: '3'
services:
  web:
    depends_on:
      - java-analyzer
    build: ./web
    ports:
      - "80:5000"
    volumes:
      - shared_volume:/shared
    environment:
      JAVA_ANALYZER_URL: http://java-analyzer:8080/analyze
      AUTH_USERNAME: "admin"
      AUTH_PASSWORD: "password"

  java-analyzer:
    build: ./java
    volumes:
      - shared_volume:/shared

volumes:
  shared_volume:
